# Game client settings for the recorded session; passed with --config.
name = Jev
screen_w = 1280
screen_h = 720
autosave_screensize = false
fullscreen = false
enable_sound = false
pause_on_lost_focus = false
fps_max = 30
fps_max_unfocused = 30
viewing_range = 120
show_debug = false
secure.http_mods = jev_agent
